version: "3"
services:
  go_xml_tick:
    image: haifengat/go_xml_tick
    container_name: go_xml_tick
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - xmlFilePath=/home/xml_path
      - csvPath=/home/csv_path
    volumes: 
      - /mnt/future_xml:/home/xml_path
      - /mnt/future_tick_csv_gz:/home/csv_path
